apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: recorder
spec:
  params:
  - name: git-repo-url
    value: https://github.com/cloud-native-garage-method-cohort/kiddlin-recorder.git
    #    value: $(body.repository.url)
  - name: git-repo-name
    value: recorder
    #    value: $(body.repository.name)
  - name: git-revision
    value: main
    #    value: $(body.head_commit.id)