apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
<<<<<<< HEAD
  name: recorder-pipiline
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: deployment-name
      type: string
      description: name of the deployment to be patched
    - name: git-url
      type: string
      description: url of the git repo for the code of deployment
    - name: git-revision
      type: string
      description: revision to be used from repo of the code for deployment
      default: "main"
    - name: IMAGE
      type: string
      description: image to be build from the code
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
    - name: build-image
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: TLSVERIFY
          value: "false"
        - name: IMAGE
          value: $(params.IMAGE)
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - fetch-repository
    - name: apply-manifests
      taskRef:
        name: apply-manifests
      workspaces:
        - name: output
          workspace: shared-workspace
      runAfter:
        - build-image
    - name: update-deployment
      taskRef:
        name: update-deployment
      params:
        - name: deployment
          value: $(params.deployment-name)
        - name: IMAGE
          value: $(params.IMAGE)
      runAfter:
        - apply-manifests
=======
  annotations:
    app.openshift.io/runtime: python
  name: squad5-api-pipeline
spec:
   workspaces:
      - name: pipeline-shared-data
        description: This workspace stores the cloned repository and is available to all steps
   params:
     - name: image-repo
       type: string
       description: Docker image name
       default: quay.io/min_ji_gz_ibm/cloudnative  
   tasks:
     - name: squad5-fetch-repository
       params:
         - name: url
           value: https://github.com/cloud-native-garage-method-cohort/squad5-api-repo
        #  - name: revision
        #    value: dev
         - name: deleteExisting
           value: "true"
       taskRef:
         kind: Task
         name: git-clone
       workspaces:
         - name: output
           workspace: pipeline-shared-data
    #  - name: squad5-install-dependencies
    #    taskRef:
    #      name: npm
    #    workspaces:
    #      - name: source
    #        workspace: pipeline-shared-data
    #    params:
    #      - name: PATH_CONTEXT
    #        value: "app"
    #      - name: ARGS
    #        value:
    #          - clean-install
    #    runAfter:
    #      - miles-ji-fetch-repository
    #  - name: miles-ji-run-test
    #    taskRef:
    #      name: npm
    #    workspaces:
    #      - name: source
    #        workspace: pipeline-shared-data
    #    params:
    #      - name: PATH_CONTEXT
    #        value: "app"
    #      - name: ARGS
    #        value:
    #          - test
    #    runAfter:
    #      - miles-ji-install-dependencies
     - name: build-image
       runAfter:
         - squad5-fetch-repository
       params:
         - name: IMAGE
           value: "$(params.image-repo):$(tasks.squad5-fetch-repository.results.commit)"
       taskRef:
         kind: Task
         name: buildah
       workspaces:
         - name: source
           workspace: pipeline-shared-data
         - name: sslcertdir
           workspace: pipeline-shared-data
     - name: kustomize-build
       runAfter:
         - build-image
       params:
         - name: image-with-tag
           value: "quay.io/min_ji_gz_ibm/cloudnative/squad5-api=$(params.image-repo):$(tasks.squad5-fetch-repository.results.commit)"
         - name: app-namespace
           value: miles-ji-pipeline-from-scratch
         - name: app-name
           value: squad5-pipeline-from-scratch
       taskRef:
         kind: Task
         name: kustomize-build
       workspaces:
         - name: source
           workspace: pipeline-shared-data
     - name: test-deploy
       runAfter:
         - kustomize-build
       params:
         - name: app-namespace
           value: miles-ji-pipeline-from-scratch
         - name: app-name
           value: squad5-pipeline-from-scratch
       taskRef:
         kind: Task
         name: test-deploy
       workspaces:
         - name: source
           workspace: pipeline-shared-data
     - name: gitops
       runAfter:
         - test-deploy
       taskRef:
         kind: Task
         name: gitops
       params:
        - name: app-name
          value: squad5-pipeline-from-scratch
        - name: sha
          value: "$(tasks.squad5-fetch-repository.results.commit)"
       workspaces:
        - name: source
          workspace: pipeline-shared-data
>>>>>>> 58128d4cea2b5d206b420fbff852f417e0c7926f
