apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
commonLabels:
  app: recorder
  app.kubernetes.io/instance: recorder
  app.kubernetes.io/name: recorder