apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: recorder-pipilinerun-
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: recorder-pipiline
  params:
    - name: deployment-name
      value: recorder
    - name: git-url
      value: https://github.com/cloud-native-garage-method-cohort/kiddlin-recorder.git
    - name: IMAGE
      value: quay.io/kiddlin/recorder:latest
  workspaces:
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: kaidilin-tekton-pvc
